/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApiRadikoPlaylistRouteImport } from "./routes/api/radiko/playlist";
import { Route as ApiRadikoAuthRouteImport } from "./routes/api/radiko/auth";
import { Route as ApiRadikoSplatRouteImport } from "./routes/api/radiko/$";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiRadikoPlaylistRoute = ApiRadikoPlaylistRouteImport.update({
  id: "/api/radiko/playlist",
  path: "/api/radiko/playlist",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiRadikoAuthRoute = ApiRadikoAuthRouteImport.update({
  id: "/api/radiko/auth",
  path: "/api/radiko/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiRadikoSplatRoute = ApiRadikoSplatRouteImport.update({
  id: "/api/radiko/$",
  path: "/api/radiko/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/api/radiko/$": typeof ApiRadikoSplatRoute;
  "/api/radiko/auth": typeof ApiRadikoAuthRoute;
  "/api/radiko/playlist": typeof ApiRadikoPlaylistRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/api/radiko/$": typeof ApiRadikoSplatRoute;
  "/api/radiko/auth": typeof ApiRadikoAuthRoute;
  "/api/radiko/playlist": typeof ApiRadikoPlaylistRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/api/radiko/$": typeof ApiRadikoSplatRoute;
  "/api/radiko/auth": typeof ApiRadikoAuthRoute;
  "/api/radiko/playlist": typeof ApiRadikoPlaylistRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/api/radiko/$"
    | "/api/radiko/auth"
    | "/api/radiko/playlist";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/api/radiko/$" | "/api/radiko/auth" | "/api/radiko/playlist";
  id:
    | "__root__"
    | "/"
    | "/api/radiko/$"
    | "/api/radiko/auth"
    | "/api/radiko/playlist";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApiRadikoSplatRoute: typeof ApiRadikoSplatRoute;
  ApiRadikoAuthRoute: typeof ApiRadikoAuthRoute;
  ApiRadikoPlaylistRoute: typeof ApiRadikoPlaylistRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/radiko/playlist": {
      id: "/api/radiko/playlist";
      path: "/api/radiko/playlist";
      fullPath: "/api/radiko/playlist";
      preLoaderRoute: typeof ApiRadikoPlaylistRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/radiko/auth": {
      id: "/api/radiko/auth";
      path: "/api/radiko/auth";
      fullPath: "/api/radiko/auth";
      preLoaderRoute: typeof ApiRadikoAuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/radiko/$": {
      id: "/api/radiko/$";
      path: "/api/radiko/$";
      fullPath: "/api/radiko/$";
      preLoaderRoute: typeof ApiRadikoSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRadikoSplatRoute: ApiRadikoSplatRoute,
  ApiRadikoAuthRoute: ApiRadikoAuthRoute,
  ApiRadikoPlaylistRoute: ApiRadikoPlaylistRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
